version: 2

ubuntu_amd64: &ubuntu_amd64
    resource_class: medium
    machine:
        image: ubuntu-2404:current

ubuntu_arm64: &ubuntu_arm64
    resource_class: arm.medium
    machine:
        image: ubuntu-2404:current

bootstrap: &bootstrap
    name: Bootstrap test OS
    command: |
        git clone --depth 1 --branch cicd_fixes https://github.com/kube-reactor/core.git /tmp/reactor
        /tmp/reactor/install.sh

session: &session
    name: Test Project Cluster
    command:
        /tmp/reactor/bin/reactor test --name=test --cicd

session_env: &session_env
    MINIKUBE_CPUS: 2
    MINIKUBE_MEMORY: 6144

test_bash: &test_bash
    steps:
        - checkout
        - run:
            <<: *bootstrap
            shell: /usr/bin/bash
            environment: *session_env
        - run:
            <<: *session
            shell: /usr/bin/bash
            environment: *session_env

jobs:
    test-amd64-ubuntu-bash:
        <<: [*ubuntu_amd64, *test_bash]

    test-arm64-ubuntu-bash:
        <<: [*ubuntu_arm64, *test_bash]

workflows:
    version: 2
    deploy:
        jobs:
            - test-amd64-ubuntu-bash:
                filters:
                    tags:
                        only: /.*/

            - test-arm64-ubuntu-bash:
                filters:
                    tags:
                        only: /.*/
